add rc.local edits

diff --git a/README b/README
--- a/README
+++ b/README
@@ -1,1 +1,10 @@
 This is basically a simple form of shadow/unshadow kind of thingy for Linux CAPABILITIES(7)
+Add to /etc/rc.d/rc.local
+
+if [ -x /etc/rc.d/rc.pcaps4suid0 ]; then
+  if ! /etc/rc.d/rc.pcaps4suid0 start ; then
+    echo "Error: /etc/rc.d/rc.pcaps4suid0 start" >&2
+  fi
+fi
+
+And maybe a stop to rc.local_shutdown 
