correct error message

diff --git a/root/bin/groups4suid0 b/root/bin/groups4suid0
--- a/root/bin/groups4suid0
+++ b/root/bin/groups4suid0
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-#   Search for suid binaries, and put them in thier own groups.
+#   Search for setuid-root binaries, and put them in thier own groups.
 #
 
 # Written by Menno Duursma <druiloor@zonnet.nl>
@@ -46,7 +46,7 @@ for f in `find "$DIR" -mount -type f -uid 0 -perm +4000 -print`; do
 
     # Both SUID and SGID (procmail still worksForMe just SGID):
     if ! chmod u-s,g+s-r,o-r $f ; then
-      echo "Error: chmod u-s,g+s,o-r $f" >&2
+      echo "Error: chmod u-s,g+s-r,o-r $f" >&2
     fi
 
   elif [ "$SUIDEXEC" == "yes" ]; then
