use system rather than user groups

diff --git a/root/bin/groups4suid0 b/root/bin/groups4suid0
--- a/root/bin/groups4suid0
+++ b/root/bin/groups4suid0
@@ -13,14 +13,14 @@ else
   DIR="$1"
 fi
 
-for f in `find "/$DIR" -mount -type f -perm +4000 -print`; do
+for f in `find "$DIR" -mount -type f -perm +4000 -print`; do
   # Convert file names to lowercase and stuff it in F
   F=`echo $f |tr '[A-Z]' '[a-z]'`
 
   # Create groups if they don't already exist
   if ! grep -q "^`basename $F`:" /etc/group; then
-    if ! groupadd `basename $F` ; then
-      echo "Error: groupadd `basename $F`" >&2
+    if ! groupadd -r `basename $F` ; then
+      echo "Error: groupadd  -r `basename $F`" >&2
     fi
   fi
 
@@ -45,12 +45,12 @@ for f in `find "/$DIR" -mount -type f -perm +4000 -print`; do
 
   # Set the file protection bits:
   if [ "$SUIDEXEC" == "yes" -a "$SGIDEXEC" == "yes" ]; then
-    # Both SUID and SGID:
-    if ! chmod 6750 $f ; then
-      echo "Error: chmod 6750 $f" >&2
+    # Both SUID and SGID (procmail still worksForMe just SGID):
+    if ! chmod u-s,g+s,o-r $f ; then
+      echo "Error: chmod u-s,g+s,o-r $f" >&2
     fi
   elif [ "$SUIDEXEC" == "yes" ]; then
-    # Just SUID:
+    # SUID:
     if ! chmod 4750 $f ; then
       echo "Error: chmod 4750 $f" >&2
     fi
